[package]
name = "vehicle_parser"
version = "0.1.0"
edition = "2021"
authors = ["Artem Shylov"]
description = "Parse data about vehicles to json"
license = "MIT" 

[dependencies]
anyhow = "1.0.93"
pest = "2.7.14"
pest_derive = "2.7.14"
serde_json = "1.0.132"
thiserror = "2.0.3"
